/*

 CITYMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : G:\WORK\HomeBrews\GB\Projects\CityWorm\sourcefiles\City.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __cityMap_h_INCLUDE
#define __cityMap_h_INCLUDE

#define M_CityMapWidth 32
#define M_CityMapHeight 32
#define M_CityMapBank 0

extern const unsigned char M_CityMap[];

#endif

/* End of CITYMAP.H */
