/*

 CITY.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 39

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __city_h_INCLUDE
#define __city_h_INCLUDE

/* Bank of tiles. */
#define T_CityBank 0
/* Start of tile array. */
extern const unsigned char T_City[];
#define T_CityLen 40

#endif

/* End of CITY.H */
