/*

 WORM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __worm_h_INCLUDE
#define __worm_h_INCLUDE

/* Bank of tiles. */
#define T_WormBank 0
/* Start of tile array. */
extern const unsigned char T_Worm[];
#define T_WormLen 36

#endif

/* End of WORM.H */
